name: Trajectly
description: >
  Deterministic regression testing for AI agents.
  Thin wrapper around the trajectly CLI — no TRT logic lives here.
branding:
  icon: check-circle
  color: blue

inputs:
  spec_glob:
    description: Glob pattern for agent spec files
    required: false
    default: "specs/*.agent.yaml"
  project_root:
    description: Root directory of the project
    required: false
    default: "."
  python_version:
    description: Python version to use
    required: false
    default: "3.11"
  install:
    description: 'How to install trajectly: "editable" (pip install -e .) or "pypi" (pip install trajectly)'
    required: false
    default: editable
  comment_pr:
    description: Post a PR comment with the report summary
    required: false
    default: "true"
  upload_artifacts:
    description: Upload .trajectly/** as build artifacts
    required: false
    default: "true"

runs:
  using: composite
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python_version }}

    - name: Install Trajectly
      shell: bash
      run: |
        if [ "${{ inputs.install }}" = "pypi" ]; then
          pip install trajectly
        else
          pip install -e "${{ inputs.project_root }}"
        fi

    - name: Run specs
      id: run
      shell: bash
      working-directory: ${{ inputs.project_root }}
      run: |
        set +e
        trajectly run ${{ inputs.spec_glob }} --project-root .
        echo "exit_code=$?" >> "$GITHUB_OUTPUT"
      continue-on-error: true

    - name: Generate PR comment report
      if: always()
      shell: bash
      working-directory: ${{ inputs.project_root }}
      run: |
        trajectly report --pr-comment > trajectly_pr_comment.md 2>/dev/null || true

    - name: Post PR comment
      if: inputs.comment_pr == 'true' && github.event_name == 'pull_request' && always()
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');
          const commentPath = '${{ inputs.project_root }}/trajectly_pr_comment.md';
          if (!fs.existsSync(commentPath)) return;
          const body = fs.readFileSync(commentPath, 'utf8').trim();
          if (!body) return;

          const { data: comments } = await github.rest.issues.listComments({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number,
          });
          const marker = '<!-- trajectly-report -->';
          const existing = comments.find(c => c.body.includes(marker));
          const fullBody = `${marker}\n${body}`;
          if (existing) {
            await github.rest.issues.updateComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: existing.id,
              body: fullBody,
            });
          } else {
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: fullBody,
            });
          }

    - name: Upload artifacts
      if: inputs.upload_artifacts == 'true' && always()
      uses: actions/upload-artifact@v4
      with:
        name: trajectly-results
        path: ${{ inputs.project_root }}/.trajectly/**
        if-no-files-found: ignore

    - name: Propagate exit code
      shell: bash
      run: exit ${{ steps.run.outputs.exit_code || 0 }}
