name: scorecard

on:
  branch_protection_rule:
  schedule:
    - cron: "30 7 * * 1"
  push:
    branches:
      - main
  workflow_dispatch:

permissions: read-all

jobs:
  analysis:
    name: OSSF Scorecard analysis
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      id-token: write
      contents: read
      actions: read

    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          persist-credentials: false

      - name: Run OSSF Scorecard
        uses: ossf/scorecard-action@4eaacf0543bb3f2c246792bd56e8cdeffafb205a # v2.4.3
        with:
          results_file: results.sarif
          results_format: sarif
          publish_results: true

      - name: Upload SARIF to code scanning
        uses: github/codeql-action/upload-sarif@ccdb31a30b64f237d5e093766753e134dd045e07 # v3.32.5
        with:
          sarif_file: results.sarif
